export const table = [

        "Department Name", "Head of Department", "Number if Staff", "Location", "Bed Capacity", "Specialty", "Equipment", "Action" ]


        export const initialData =[
          {
              departmentName: "Cardiology",
              headOfDepartment: "Dr. Smith",
              numberOfStaff: 10,
              location: "Building A",
              bedCapacity: 20,
              specialty: "Heart Care",
              equipment: "ECG, Echo Machine",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Neurology",
              headOfDepartment: "Dr. Johnson",
              numberOfStaff: 8,
              location: "Building B",
              bedCapacity: 15,
              specialty: "Brain Disorders",
              equipment: "MRI, EEG",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Pediatrics",
              headOfDepartment: "Dr. Lee",
              numberOfStaff: 12,
              location: "Building C",
              bedCapacity: 25,
              specialty: "Children's Health",
              equipment: "Pediatric Scale, Vaccination Kit",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Oncology",
              headOfDepartment: "Dr. Patel",
              numberOfStaff: 15,
              location: "Building D",
              bedCapacity: 30,
              specialty: "Cancer Treatment",
              equipment: "Chemotherapy Chairs, Radiotherapy Machine",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Orthopedics",
              headOfDepartment: "Dr. Davis",
              numberOfStaff: 9,
              location: "Building E",
              bedCapacity: 18,
              specialty: "Bone & Joint Care",
              equipment: "X-ray Machine, Casting Tools",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Dermatology",
              headOfDepartment: "Dr. Garcia",
              numberOfStaff: 7,
              location: "Building F",
              bedCapacity: 10,
              specialty: "Skin Conditions",
              equipment: "Dermatoscope, Laser Treatment",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Gastroenterology",
              headOfDepartment: "Dr. Wilson",
              numberOfStaff: 5,
              location: "Building G",
              bedCapacity: 12,
              specialty: "Digestive System",
              equipment: "Endoscope, Ultrasound Machine",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Radiology",
              headOfDepartment: "Dr. Thompson",
              numberOfStaff: 11,
              location: "Building H",
              bedCapacity: 20,
              specialty: "Medical Imaging",
              equipment: "CT Scanner, MRI Machine",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Anesthesiology",
              headOfDepartment: "Dr. Martinez",
              numberOfStaff: 6,
              location: "Building I",
              bedCapacity: 8,
              specialty: "Pain Management",
              equipment: "Anesthesia Machine, Monitors",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Urology",
              headOfDepartment: "Dr. Hernandez",
              numberOfStaff: 4,
              location: "Building J",
              bedCapacity: 6,
              specialty: "Urinary Tract",
              equipment: "Cystoscope, Ultrasound Machine",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Ophthalmology",
              headOfDepartment: "Dr. Clark",
              numberOfStaff: 5,
              location: "Building K",
              bedCapacity: 10,
              specialty: "Eye Care",
              equipment: "Slit Lamp, Retinal Camera",
              actions: ["View", "Edit", "Print", "Delete"],
          },
          {
              departmentName: "Endocrinology",
              headOfDepartment: "Dr. Lewis",
              numberOfStaff: 3,
              location: "Building L",
              bedCapacity: 5,
              specialty: "Hormonal Disorders",
              equipment: "Glucose Meter, Hormone Assay Kit",
              actions: ["View", "Edit", "Print", "Delete"],
          },
      ];



