import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

// Define a base URL for the API
const BASE_URL = "https://be-ems.onrender.com/api/v1";

// Create the staff API slice
const staffApi = createApi({
  reducerPath: "staffApi", // Keeps the name for clarity
  baseQuery: fetchBaseQuery({ baseUrl: BASE_URL }),
  endpoints: (builder) => ({
    fetchStaff: builder.query({
      query: (endpoint) => endpoint, // Using endpoint for better clarity
    }),
    editStaff: builder.mutation({
      query: ({ endpoint, data }) => ({
        url: endpoint,
        method: "PUT",
        body: JSON.stringify(data), // Ensure data is stringified
        headers: { "Content-Type": "application/json" },
      }),
    }),
    createStaff: builder.mutation({
      // Renamed for clarity
      query: ({ data }) => ({
        url: "/staff/create",
        method: "POST",
        body: JSON.stringify(data), // Ensure data is stringified
        headers: { "Content-Type": "application/json" },
      }),
    }),
    deleteStaff: builder.mutation({
      query: (endpoint) => ({
        url: endpoint,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks generated by createApi
export const {
  useFetchStaffQuery,
  useEditStaffMutation,
  useCreateStaffMutation,
  useDeleteStaffMutation,
} = staffApi;

// Export the staffApi itself for integration in the store
export default staffApi;
